import re

PRODUCT_FIXTURES: dict[str, list[dict]] = {
    "milk": [
        {
            "itemId": 10452064,
            "name": "Great Value Whole Milk",
            "brandName": "Great Value",
            "upc": "0078742365169",
            "size": "1 gal",
            "salePrice": 3.48,
            "msrp": 3.48,
            "categoryPath": "Food/Dairy & Eggs/Milk",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Milk",
            "stock": "Available",
        },
        {
            "itemId": 10452065,
            "name": "Horizon Organic Whole Milk",
            "brandName": "Horizon",
            "upc": "0074609803002",
            "size": "1 gal",
            "salePrice": 5.48,
            "msrp": 6.29,
            "categoryPath": "Food/Dairy & Eggs/Milk",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Milk",
            "stock": "Available",
        },
        {
            "itemId": 10452066,
            "name": "Fairlife Whole Milk Ultra-Filtered",
            "brandName": "Fairlife",
            "upc": "0041383060012",
            "size": "52 fl oz",
            "salePrice": 4.94,
            "msrp": 5.48,
            "categoryPath": "Food/Dairy & Eggs/Milk",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Milk",
            "stock": "Available",
        },
    ],
    "eggs": [
        {
            "itemId": 22023340,
            "name": "Great Value Large White Eggs",
            "brandName": "Great Value",
            "upc": "0078742195278",
            "size": "12 ct",
            "salePrice": 2.84,
            "msrp": 2.84,
            "categoryPath": "Food/Dairy & Eggs/Eggs",
            "largeImage": "https://placehold.co/80x80/fff9c4/f57f17?text=Eggs",
            "stock": "Available",
        },
        {
            "itemId": 22023341,
            "name": "Eggland's Best Classic Large White Eggs",
            "brandName": "Eggland's Best",
            "upc": "0071018500116",
            "size": "12 ct",
            "salePrice": 3.98,
            "msrp": 4.48,
            "categoryPath": "Food/Dairy & Eggs/Eggs",
            "largeImage": "https://placehold.co/80x80/fff9c4/f57f17?text=Eggs",
            "stock": "Available",
        },
        {
            "itemId": 22023342,
            "name": "Vital Farms Pasture-Raised Eggs",
            "brandName": "Vital Farms",
            "upc": "0894658000010",
            "size": "12 ct",
            "salePrice": 6.98,
            "msrp": 7.49,
            "categoryPath": "Food/Dairy & Eggs/Eggs",
            "largeImage": "https://placehold.co/80x80/fff9c4/f57f17?text=Eggs",
            "stock": "Available",
        },
    ],
    "bread": [
        {
            "itemId": 43778100,
            "name": "Wonder Classic White Bread",
            "brandName": "Wonder",
            "upc": "0007203100036",
            "size": "20 oz",
            "salePrice": 2.48,
            "msrp": 2.98,
            "categoryPath": "Food/Bakery/Bread",
            "largeImage": "https://placehold.co/80x80/ffe0b2/e65100?text=Bread",
            "stock": "Available",
        },
        {
            "itemId": 43778101,
            "name": "Dave's Killer Bread 21 Whole Grains",
            "brandName": "Dave's Killer Bread",
            "upc": "0001380000001",
            "size": "27 oz",
            "salePrice": 5.48,
            "msrp": 5.99,
            "categoryPath": "Food/Bakery/Bread",
            "largeImage": "https://placehold.co/80x80/ffe0b2/e65100?text=Bread",
            "stock": "Available",
        },
        {
            "itemId": 43778102,
            "name": "Nature's Own Honey Wheat Bread",
            "brandName": "Nature's Own",
            "upc": "0072250000001",
            "size": "20 oz",
            "salePrice": 3.28,
            "msrp": 3.98,
            "categoryPath": "Food/Bakery/Bread",
            "largeImage": "https://placehold.co/80x80/ffe0b2/e65100?text=Bread",
            "stock": "Available",
        },
    ],
    "chicken": [
        {
            "itemId": 15568500,
            "name": "Freshness Guaranteed Boneless Skinless Chicken Breasts",
            "brandName": "Freshness Guaranteed",
            "upc": "0078742052236",
            "size": "per lb",
            "salePrice": 3.98,
            "msrp": 3.98,
            "categoryPath": "Food/Fresh & Frozen/Fresh Chicken",
            "largeImage": "https://placehold.co/80x80/fce4ec/880e4f?text=Chicken",
            "stock": "Available",
        },
        {
            "itemId": 15568501,
            "name": "Great Value Frozen Boneless Skinless Chicken Breasts",
            "brandName": "Great Value",
            "upc": "0078742185828",
            "size": "3 lb",
            "salePrice": 8.98,
            "msrp": 9.98,
            "categoryPath": "Food/Fresh & Frozen/Frozen Chicken",
            "largeImage": "https://placehold.co/80x80/fce4ec/880e4f?text=Chicken",
            "stock": "Available",
        },
        {
            "itemId": 15568502,
            "name": "Tyson Boneless Skinless Chicken Breasts",
            "brandName": "Tyson",
            "upc": "0002320000001",
            "size": "2.5 lb",
            "salePrice": 9.97,
            "msrp": 11.28,
            "categoryPath": "Food/Fresh & Frozen/Fresh Chicken",
            "largeImage": "https://placehold.co/80x80/fce4ec/880e4f?text=Chicken",
            "stock": "Available",
        },
    ],
    "apples": [
        {
            "itemId": 30455522,
            "name": "Fresh Gala Apples",
            "brandName": "",
            "upc": "0000000004131",
            "size": "per lb",
            "salePrice": 1.28,
            "msrp": 1.48,
            "categoryPath": "Food/Fresh Produce/Fresh Fruits",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Apples",
            "stock": "Available",
        },
        {
            "itemId": 30455523,
            "name": "Fresh Honeycrisp Apples",
            "brandName": "",
            "upc": "0000000003283",
            "size": "per lb",
            "salePrice": 2.48,
            "msrp": 2.98,
            "categoryPath": "Food/Fresh Produce/Fresh Fruits",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Apples",
            "stock": "Available",
        },
        {
            "itemId": 30455524,
            "name": "Cosmic Crisp Apples 3 lb Bag",
            "brandName": "",
            "upc": "0000000000001",
            "size": "3 lb bag",
            "salePrice": 3.98,
            "msrp": 4.98,
            "categoryPath": "Food/Fresh Produce/Fresh Fruits",
            "largeImage": "https://placehold.co/80x80/e8f5e9/1b5e20?text=Apples",
            "stock": "Available",
        },
    ],
    "butter": [
        {
            "itemId": 10317593,
            "name": "Great Value Unsalted Butter Sticks",
            "brandName": "Great Value",
            "upc": "0078742181430",
            "size": "16 oz",
            "salePrice": 3.44,
            "msrp": 3.44,
            "categoryPath": "Food/Dairy & Eggs/Butter & Margarine",
            "largeImage": "https://placehold.co/80x80/fff8e1/ff6f00?text=Butter",
            "stock": "Available",
        },
        {
            "itemId": 10317594,
            "name": "Kerrygold Pure Irish Butter",
            "brandName": "Kerrygold",
            "upc": "0073992000001",
            "size": "8 oz",
            "salePrice": 4.48,
            "msrp": 4.98,
            "categoryPath": "Food/Dairy & Eggs/Butter & Margarine",
            "largeImage": "https://placehold.co/80x80/fff8e1/ff6f00?text=Butter",
            "stock": "Available",
        },
        {
            "itemId": 10317595,
            "name": "Land O Lakes Salted Butter",
            "brandName": "Land O Lakes",
            "upc": "0007020021001",
            "size": "16 oz",
            "salePrice": 4.78,
            "msrp": 5.29,
            "categoryPath": "Food/Dairy & Eggs/Butter & Margarine",
            "largeImage": "https://placehold.co/80x80/fff8e1/ff6f00?text=Butter",
            "stock": "Available",
        },
    ],
    "cheese": [
        {
            "itemId": 14967100,
            "name": "Great Value Medium Cheddar Cheese Block",
            "brandName": "Great Value",
            "upc": "0078742170411",
            "size": "16 oz",
            "salePrice": 4.96,
            "msrp": 4.96,
            "categoryPath": "Food/Dairy & Eggs/Cheese",
            "largeImage": "https://placehold.co/80x80/fff3e0/bf360c?text=Cheese",
            "stock": "Available",
        },
        {
            "itemId": 14967101,
            "name": "Kraft Mexican Style Finely Shredded Cheese",
            "brandName": "Kraft",
            "upc": "0002100077001",
            "size": "8 oz",
            "salePrice": 2.97,
            "msrp": 3.28,
            "categoryPath": "Food/Dairy & Eggs/Cheese",
            "largeImage": "https://placehold.co/80x80/fff3e0/bf360c?text=Cheese",
            "stock": "Available",
        },
    ],
    "yogurt": [
        {
            "itemId": 14636900,
            "name": "Chobani Plain Greek Yogurt",
            "brandName": "Chobani",
            "upc": "0081840000010",
            "size": "32 oz",
            "salePrice": 4.98,
            "msrp": 5.49,
            "categoryPath": "Food/Dairy & Eggs/Yogurt",
            "largeImage": "https://placehold.co/80x80/e3f2fd/0d47a1?text=Yogurt",
            "stock": "Available",
        },
        {
            "itemId": 14636901,
            "name": "Great Value Vanilla Non-fat Yogurt",
            "brandName": "Great Value",
            "upc": "0078742150000",
            "size": "32 oz",
            "salePrice": 2.98,
            "msrp": 2.98,
            "categoryPath": "Food/Dairy & Eggs/Yogurt",
            "largeImage": "https://placehold.co/80x80/e3f2fd/0d47a1?text=Yogurt",
            "stock": "Available",
        },
    ],
    "pasta": [
        {
            "itemId": 10409820,
            "name": "Barilla Penne Rigate Pasta",
            "brandName": "Barilla",
            "upc": "0076808000001",
            "size": "16 oz",
            "salePrice": 1.58,
            "msrp": 1.88,
            "categoryPath": "Food/Pantry/Pasta, Rice & Grains",
            "largeImage": "https://placehold.co/80x80/f3e5f5/4a148c?text=Pasta",
            "stock": "Available",
        },
        {
            "itemId": 10409821,
            "name": "Great Value Penne Rigate",
            "brandName": "Great Value",
            "upc": "0078742192451",
            "size": "16 oz",
            "salePrice": 0.88,
            "msrp": 0.88,
            "categoryPath": "Food/Pantry/Pasta, Rice & Grains",
            "largeImage": "https://placehold.co/80x80/f3e5f5/4a148c?text=Pasta",
            "stock": "Available",
        },
    ],
    "rice": [
        {
            "itemId": 10782785,
            "name": "Great Value Long Grain White Rice",
            "brandName": "Great Value",
            "upc": "0078742136134",
            "size": "5 lb",
            "salePrice": 2.54,
            "msrp": 2.54,
            "categoryPath": "Food/Pantry/Pasta, Rice & Grains",
            "largeImage": "https://placehold.co/80x80/f9fbe7/33691e?text=Rice",
            "stock": "Available",
        },
        {
            "itemId": 10782786,
            "name": "Mahatma Long Grain White Rice",
            "brandName": "Mahatma",
            "upc": "0007445500001",
            "size": "5 lb",
            "salePrice": 4.48,
            "msrp": 4.98,
            "categoryPath": "Food/Pantry/Pasta, Rice & Grains",
            "largeImage": "https://placehold.co/80x80/f9fbe7/33691e?text=Rice",
            "stock": "Available",
        },
    ],
    "coffee": [
        {
            "itemId": 19102490,
            "name": "Folgers Classic Roast Ground Coffee",
            "brandName": "Folgers",
            "upc": "0002550042705",
            "size": "11.3 oz",
            "salePrice": 6.98,
            "msrp": 7.98,
            "categoryPath": "Food/Beverages/Coffee",
            "largeImage": "https://placehold.co/80x80/3e2723/ffffff?text=Coffee",
            "stock": "Available",
        },
        {
            "itemId": 19102491,
            "name": "Great Value 100% Arabica Medium Roast Ground Coffee",
            "brandName": "Great Value",
            "upc": "0078742188552",
            "size": "12 oz",
            "salePrice": 5.48,
            "msrp": 5.48,
            "categoryPath": "Food/Beverages/Coffee",
            "largeImage": "https://placehold.co/80x80/3e2723/ffffff?text=Coffee",
            "stock": "Available",
        },
    ],
    "orange juice": [
        {
            "itemId": 10451460,
            "name": "Simply Orange Pulp Free Orange Juice",
            "brandName": "Simply",
            "upc": "0025000052750",
            "size": "52 oz",
            "salePrice": 4.28,
            "msrp": 4.98,
            "categoryPath": "Food/Beverages/Juice",
            "largeImage": "https://placehold.co/80x80/fff3e0/e65100?text=OJ",
            "stock": "Available",
        },
        {
            "itemId": 10451461,
            "name": "Great Value Orange Juice 100%",
            "brandName": "Great Value",
            "upc": "0078742178738",
            "size": "52 oz",
            "salePrice": 2.98,
            "msrp": 2.98,
            "categoryPath": "Food/Beverages/Juice",
            "largeImage": "https://placehold.co/80x80/fff3e0/e65100?text=OJ",
            "stock": "Available",
        },
    ],
    "cereal": [
        {
            "itemId": 10451570,
            "name": "Cheerios Whole Grain Oat Cereal",
            "brandName": "General Mills",
            "upc": "0001600027527",
            "size": "18 oz",
            "salePrice": 4.48,
            "msrp": 5.49,
            "categoryPath": "Food/Breakfast & Cereal",
            "largeImage": "https://placehold.co/80x80/fff8e1/f9a825?text=Cereal",
            "stock": "Available",
        },
        {
            "itemId": 10451571,
            "name": "Great Value Toasted Oats Cereal",
            "brandName": "Great Value",
            "upc": "0078742159096",
            "size": "12.25 oz",
            "salePrice": 1.98,
            "msrp": 1.98,
            "categoryPath": "Food/Breakfast & Cereal",
            "largeImage": "https://placehold.co/80x80/fff8e1/f9a825?text=Cereal",
            "stock": "Available",
        },
    ],
    "ground beef": [
        {
            "itemId": 12014787,
            "name": "All Natural 93% Lean Ground Beef",
            "brandName": "Freshness Guaranteed",
            "upc": "0078742102108",
            "size": "per lb",
            "salePrice": 5.48,
            "msrp": 5.98,
            "categoryPath": "Food/Fresh & Frozen/Fresh Beef",
            "largeImage": "https://placehold.co/80x80/fce4ec/b71c1c?text=Beef",
            "stock": "Available",
        },
        {
            "itemId": 12014788,
            "name": "All Natural 80% Lean Ground Beef",
            "brandName": "Freshness Guaranteed",
            "upc": "0078742102102",
            "size": "per lb",
            "salePrice": 4.48,
            "msrp": 4.48,
            "categoryPath": "Food/Fresh & Frozen/Fresh Beef",
            "largeImage": "https://placehold.co/80x80/fce4ec/b71c1c?text=Beef",
            "stock": "Available",
        },
    ],
    "banana": [
        {
            "itemId": 30154844,
            "name": "Fresh Bananas",
            "brandName": "Chiquita",
            "upc": "0000000004011",
            "size": "per lb",
            "salePrice": 0.57,
            "msrp": 0.57,
            "categoryPath": "Food/Fresh Produce/Fresh Fruits",
            "largeImage": "https://placehold.co/80x80/fff9c4/f57f17?text=Bananas",
            "stock": "Available",
        },
    ],
    "bananas": [
        {
            "itemId": 30154844,
            "name": "Fresh Bananas",
            "brandName": "Chiquita",
            "upc": "0000000004011",
            "size": "per lb",
            "salePrice": 0.57,
            "msrp": 0.57,
            "categoryPath": "Food/Fresh Produce/Fresh Fruits",
            "largeImage": "https://placehold.co/80x80/fff9c4/f57f17?text=Bananas",
            "stock": "Available",
        },
    ],
}


def _generic_product(query: str) -> dict:
    return {
        "itemId": hash(query) % 9999999,
        "name": f"{query.title()} (Great Value)",
        "brandName": "Great Value",
        "upc": None,
        "size": "",
        "salePrice": 3.28,
        "msrp": 3.28,
        "categoryPath": "Food/Grocery",
        "largeImage": f"https://placehold.co/80x80/e3f2fd/0d47a1?text={query[:6].title()}",
        "stock": "Available",
    }


async def search_products(query: str, zip_code: str, limit: int = 10) -> list[dict]:
    key = query.lower().strip()
    key = re.sub(r"\s+", " ", key)

    for fixture_key, products in PRODUCT_FIXTURES.items():
        if fixture_key == key or fixture_key in key or key in fixture_key:
            return products[:limit]

    words = key.split()
    for fixture_key, products in PRODUCT_FIXTURES.items():
        fk_words = fixture_key.split()
        if any(w in fk_words for w in words if len(w) > 3):
            return products[:limit]

    return [_generic_product(query)]
